### ISSUE TITLE
OSError: [WinError 6] The handle is invalid

### ISSUE THREAD

**Issue by konradre** [AIFSH/ComfyUI_V-Express#2]
[--unet_config_path UNET_CONFIG_PATH]
                    [--vae_path VAE_PATH]
                    [--audio_encoder_path AUDIO_ENCODER_PATH]
                    [--insightface_model_path INSIGHTFACE_MODEL_PATH]
                    [--denoising_unet_path DENOISING_UNET_PATH]
                    [--reference_net_path REFERENCE_NET_PATH]
                    [--v_kps_guider_path V_KPS_GUIDER_PATH]
                    [--audio_projection_path AUDIO_PROJECTION_PATH]
                    [--motion_module_path MOTION_MODULE_PATH]
                    [--retarget_strategy RETARGET_STRATEGY]
                    [--device DEVICE] [--gpu_id GPU_ID]
                    [--dtype DTYPE]
                    [--num_pad_audio_frames NUM_PAD_AUDIO_FRAMES]
                    [--standard_audio_sampling_rate STANDARD_AUDIO_SAMPLING_RATE]
                    [--reference_image_path REFERENCE_IMAGE_PATH]
                    [--audio_path AUDIO_PATH]
                    [--kps_path KPS_PATH]
                    [--output_path OUTPUT_PATH]
                    [--image_width IMAGE_WIDTH]
                    [--image_height IMAGE_HEIGHT] [--fps FPS]
                    [--seed SEED]
                    [--num_inference_steps NUM_INFERENCE_STEPS]
                    [--guidance_scale GUIDANCE_SCALE]
                    [--context_frames CONTEXT_FRAMES]
                    [--context_stride CONTEXT_STRIDE]
                    [--context_overlap CONTEXT_OVERLAP]
                    [--reference_attention_weight REFERENCE_ATTENTION_WEIGHT]
                    [--audio_attention_weight AUDIO_ATTENTION_WEIGHT]
inference.py: error: unrecognized arguments: 0.5457, 0.5108],
Prompt executed in 90.32 seconds
Exception ignored in: <function FFMPEG_VideoReader.__del__ at 0x000001450852DE10>
Traceback (most recent call last):
  File "D:\ComfyUI\venv\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 199, in __del__
    self.close()
  File "D:\ComfyUI\venv\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 190, in close
    self.proc.terminate()
  File "C:\ProgramData\miniconda3\lib\subprocess.py", line 1573, in terminate
    _winapi.TerminateProcess(self._handle, 1)
OSError: [WinError 6] The handle is invalid

**Comment by konradre** [comment]
Traceback (most recent call last):
  File "D:\ComfyUI\custom_nodes\ComfyUI_V-Express\V_Express\inference.py", line 17, in <module>
    from modules import UNet2DConditionModel, UNet3DConditionModel, VKpsGuider, AudioProjection
  File "D:\ComfyUI\custom_nodes\ComfyUI_V-Express\V_Express\modules\__init__.py", line 1, in <module>
    from .unet_2d_condition import UNet2DConditionModel
  File "D:\ComfyUI\custom_nodes\ComfyUI_V-Express\V_Express\modules\unet_2d_condition.py", line 18, in <module>
    from diffusers.models.embeddings import (
ImportError: cannot import name 'PositionNet' from 'diffusers.models.embeddings' (D:\ComfyUI\venv\lib\site-packages\diffusers\models\embeddings.py)

**Comment by konradre** [comment]
Now getting:

inference.py: error: unrecognized arguments: 0.4745, 0.4667],

Task exception was never retrieved
future: <Task finished name='Task-357' coro=<RequestHandler.start() done, defined at D:\ComfyUI\venv\lib\site-packages\aiohttp\web_protocol.py:481> exception=AssertionError()>
Traceback (most recent call last):
  File "D:\ComfyUI\venv\lib\site-packages\aiohttp\web_protocol.py", line 524, in start
    request = self._request_factory(message, payload, self, writer, handler)
  File "D:\ComfyUI\venv\lib\site-packages\aiohttp\web_app.py", line 485, in _make_request
    return _cls(
  File "D:\ComfyUI\venv\lib\site-packages\aiohttp\web_request.py", line 828, in __init__
    super().__init__(*args, **kwargs)
  File "D:\ComfyUI\venv\lib\site-packages\aiohttp\web_request.py", line 196, in __init__
    assert transport is not None
AssertionError

**Comment by jarry-LU** [comment]
安裝完出現:Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_V-Express\V_Express\inference.py", line 7, in <module>
    import torchaudio.functional
ModuleNotFoundError: No module named 'torchaudio'
怎麼解呢?

**Comment by konradre** [comment]
Was an issue with xformers and torch version. Updating dependencies on comfy portable install fixed it.
